name:                haskell-hcup
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- http-types
- bytestring
- aeson
- servant
- text
- servant-server
- containers
- mtl

library:
  source-dirs: src

executables:
  haskell-hcup-exe:
    main:                Main
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  haskell-hcup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hcup
